CREATE DATABASE IF NOT EXISTS usermanager CHARACTER SET utf8mb4;
USE usermanager;

CREATE TABLE usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(50) NOT NULL,
 email VARCHAR(100) NOT NULL,
 edad INT NOT NULL,
 rol ENUM('admin','user') NOT NULL
);